

- name: Downloading Erlang repos
  ansible.builtin.shell: curl -s {{item}} | bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Installing erlang and yum
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: systemctl permissions
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: |-
    Add user to server and assign full access control on / vhost.
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{roboshop_rabbitmq_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
