
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Enable nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true

- name: Remove the Directory Html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create the Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name:   Downloading the frontend file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy the roboshop configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: restart the nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes


