#- name: Copying the mongodb repo
#  ansible.builtin.copy:
#    src: mongod.repo
#    dest: /etc/yum.repos.d/mongodb.repo


- name: Copying the mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: Installing the mongodb repo
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed


- name: Install MongoDB Shell
  ansible.builtin.yum:
    name: mongodb-mongosh
    state: installed



- name: Run a js file containing MongoDB commands with pseudo-idempotency
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.robomart.website
    file: "/app/schema/{{component}}.js"
    idempotent: yes

#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.devopsb70.online
#    file: "/app/schema/{{component}}.js"
#    idempotent: yes



