#- name: Copying the mongodb repo
#  ansible.builtin.copy:
#    src: mongod.repo
#    dest: /etc/yum.repos.d/mongodb.repo


#- name: Copying the mongodb repo
#  ansible.builtin.copy:
#    src: mongodb.repo
#    dest: /etc/yum.repos.d/mongodb.repo
#
#
#- name: Installing the mongodb repo
#  ansible.builtin.yum:
#    name: mongodb-org-shell
#    state: present


#- name: Install MongoDB Shell
#  ansible.builtin.yum:
#    name: mongodb-mongosh
#    state: installed

- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
    mode: '0644'

#- name: Refresh YUM cache
#  ansible.builtin.command:
#    cmd: yum clean all && yum makecache
#  changed_when: false

- name: Install MongoDB Shell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: present




- name: Run a js file containing MongoDB commands with pseudo-idempotency
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.robomart.website
    file: "/app/schema/{{component}}.js"
    idempotent: yes

#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.devopsb70.online
#    file: "/app/schema/{{component}}.js"
#    idempotent: yes



