
- name: Disable existing Node.js module
  ansible.builtin.command:
    cmd: dnf module disable nodejs -y


- name: Enable Node.js 18 module
  ansible.builtin.command:
    cmd: dnf module enable nodejs:18 -y



- name: Install Node.js 18
  ansible.builtin.dnf:
    name: nodejs
    state: present


- name: app prerequistes
  ansible.builtin.include_tasks: "app-prereq.yaml"

- name: Installing Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest


- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yaml"

- name: loading schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yaml"
  when: schema_load