
- name: Installing python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed


- name: including app prereq file
  ansible.builtin.include_tasks: "app-prereq.yaml"


- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6



- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yaml"

- name: schema load
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yaml"
  when: schema_load