- name: Systemd setup for {{component}}
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service
    force: yes

- name: Restart the service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    daemon_reload: yes
    enabled: yes