#- name: COpy SystemD file
#  ansible.builtin.template:
#    src: "{{component}}.service"
#    dest: /etc/systemd/system/{{component}}.service



- name: COpy SystemD file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Check if the catalogue service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/catalogue.service"
  register: service_file_status

- name: Debug the existence of the catalogue service file
  debug:
    msg: "File exists: {{ service_file_status.stat.exists }}"

- name: Slurp the catalogue service file contents
  ansible.builtin.slurp:
    src: "/etc/systemd/system/catalogue.service"
  register: slurped_file

- name: Debug the contents of the catalogue service file
  debug:
    msg: "{{ slurped_file.content | b64decode }}"
  when: service_file_status.stat.exists

- name: Reload systemd to pick up new service file
  ansible.builtin.systemd:
    daemon_reload: yes
  when: service_file_status.stat.exists

- name: Start the catalogue service
  ansible.builtin.systemd:
    name: "catalogue"
    state: started
  when: service_file_status.stat.exists

- name: Enable the catalogue service to start on boot
  ansible.builtin.systemd:
    name: "catalogue"
    enabled: yes
  when: service_file_status.stat.exists


#- name: Start {{component}} Service
#  ansible.builtin.systemd:
#    name: "{{component}}"
#    daemon_reload: yes
#    enabled: yes
#    state: restarted
