- name: COpy SystemD file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service
    force: yes
  register: template_output

- name: Debug template output
  ansible.builtin.debug:
    var: template_output

- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: yes
    enabled: yes
    state: restarted
